### ISSUE TITLE
Not working with date input

### ISSUE THREAD

**Issue by Vinorcola** [chrisdavies/tiny-date-picker#18]
Hi there,

The script is not working with input of type **date**. The error says that selectionStart is not available for date type input:

    Uncaught InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('date') does not support selection.

In question, this line:
https://github.com/chrisdavies/tiny-date-picker/blob/master/tiny-date-picker.js#L111
What is the purpose of this line exactly?

**Comment by chrisdavies** [comment]
Interesting. What browser?

We can make that conditional on whether or not `selectionStart` is defined on the element. It's been a while since I wrote that code, but I *think* it had to do with getting the field to properly focus in IE. There was a sequencing problem due to the order of events, but it might also be unimportant. I'll look into it.

**Comment by chrisdavies** [comment]
Just tested it in IE, Chrome, Edge, FF, and Safari. That line doesn't seem necessary. Removed it.

Thanks for sending this in and tracking down the offending line!

**Comment by Vinorcola** [comment]
Hi,

I was using Chrome. Thanks for the fast fix ;)
