### ISSUE TITLE
need ability to access javascript events on control

### ISSUE THREAD

**Issue by jersingh** [chrisdavies/tiny-date-picker#55]
Is there a way to get standard js events passed into the select event?

I need currentTarget specifically because for my process, I need to grab which specific date control was selected on a page with multiple date controls.

The underscore and 'dp" don't seem to expose all events:

```
select: (_, dp) =>
```

Thanks

**Comment by chrisdavies** [comment]
Hm. I'm not sure exactly what you mean.

If you have multiple date input elements on your page, each of them will fire a [change event](https://developer.mozilla.org/en-US/docs/Web/Events/change) when a date is selected.

Regarding the various TinyDatePicker events, I don't think the standard DOM event will be super useful, as it is triggered by various UI elements (the "a" tag for the date, or the "today" button or whatever. That's why the second parameter to TinyDatePicker event handlers *should* always be the date picker instance itself.

The date picker instance does not currently expose the associated input element, though you can do this yourself, if you want it. 

If you want to grab the associated input any time *any* date picker event fires, you can do that in a number of ways. One way is to bind the input to your handler function. Something like this:

```js
function myHandler(_, dp, input) {
  input.focus();
}

function handlerWithInput(input, handler) {
  return (evt, dp) => handler(evt, dp, input);
}

const txt = document.querySelector('.foo');
const dp = TinyDatePicker(txt);
dp.on('select', handlerWithInput(txt, myHandler));
```

An alternative would be to stick your own property onto the date picker. Something like this:

```js
function myHandler(_, dp) {
  dp.inputElement.focus();
}

const txt = document.querySelector('.foo');
const dp = TinyDatePicker(txt);
dp.inputElement = txt;
dp.on('select', myHandler);
```

Alternatively, we could expose the input as a property on dp itself. I don't think there is a good reason why it's not exposed.

**Comment by jersingh** [comment]
Hi thanks for the reply and support. Sorry I probably didn't explain that as well as I should have and your solution might work I'm just being thick headed about it (but not on purpose.)

My project is an RoR app using simple_form to generate html and my date html inputs end up looking like this:

```
<input class="form-control string optional tiny-date" placeholder="mm/dd/yyyy" type="text" value="12/12/2017" name="loan[applicants_attributes][0][formatted_dob]" id="loan_applicants_attributes_0_formatted_dob">

<input class="form-control string optional tiny-date" placeholder="mm/dd/yyyy" type="text" value="05/01/2001" name="loan[applicants_attributes][0][start_date]" id="loan_applicants_attributes_0_start_date">
```
Those names and ids are subject to change based on backend model configurations with ActiveRecord.
I'm using babel on the project so I have js that looks something like this:
```
class MyClass {
    constructor() {
        this.initTinyDate();
    }

    initTinyDate() {
        TinyDatePicker('.tiny-date', {
            mode: 'dp-below'
        }).on('select', (_, dp, event) => {
            console.log(dp.state.selectedDate);
            const id = event.currentTarget.id;
            const name = event.currentTarget.name;
            // or something like this:
            // const name = dp.inputElement.name;
            this.makeAnAjaxCallToServer(id, name);
        });
    }
}
```

So I need to get **id** and **name** based on which TinyDate was picked through the events you provide.

I'd rather not do this:
```
const td = document.querySelector('#loan_applicants_attributes_0_formatted_dob');
```
I suppose I could add specific html classes to each TDP, but if TDP could give you access to the calling control, through the event handler...is this possible?

**Comment by chrisdavies** [comment]
Ah. I see. Yes, it would be pretty simple for me to add the input control (if there is one) to the date picker object itself.

But meanwhile, there is a workaround:

```js

document.querySelectorAll('.tiny-date').forEach((input) => {
  TinyDatePicker(input, {
      mode: 'dp-below'
  }).on('select', (_, dp) => {
      console.log(dp.state.selectedDate);
      const id = input.id;
      const name = input.name;
      // or something like this:
      // const name = dp.inputElement.name;
      this.makeAnAjaxCallToServer(id, name);
  });
});
```

**Comment by chrisdavies** [comment]
I'm going to close this, assuming the workaround worked out for you! Please let me know if it didn't. :)

**Comment by jersingh** [comment]
Worked perfectly thanks!
