### ISSUE TITLE
Selected day is mistakenly passed to the previous month.

### ISSUE THREAD

**Issue by gety9** [chrisdavies/tiny-date-picker#59]
1 Select Mar 10 2018
2 Go to previous month
3 Both Mar 10 2018 and Feb 10 2018 are shown as selected.
https://puu.sh/yTNXt/997ef0997d.mp4

**Comment by chrisdavies** [comment]
Hm. This is by design, it's just a weird edge case that both the highlighted date and the selected date can show up on the screen when a previous / next month's days are showing. But I think I'd rather it behave this way than not.

You can override it via your own CSS rule:

```css
.dp-edge-day.dp-selected {
  background: transparent;
}
```

By the way, this is a *great* bug report. I love that you gave me a video!

**Comment by kvlsrg** [comment]
Also it's need to override color:

```
.dp-edge-day.dp-selected {
  background: transparent;
  color: #AAA;
}
```
