### ISSUE TITLE
Firefox do not allow month to be changed

### ISSUE THREAD

**Issue by jakubpawlowicz** [chrisdavies/tiny-date-picker#6]
When I click on "previous" or "next" month buttons in Firefox date picker closes just as if I used "close" button.

Steps to reproduce:
1. Open Firefox 46 (also tested on 48 alpha)
2. Navigate to http://chrisdavies.github.io/tiny-date-picker/
3. Open date picker
4. Try changing month to previous / next one

I narrowed down this issue to this line: https://github.com/chrisdavies/tiny-date-picker/blob/master/tiny-date-picker.js#L62

If I get rid of `if` statement and always call `e.preventDefault()` then I can change months just fine.

**Comment by chrisdavies** [comment]
Hi Jakub. Thanks for the heads up and doing the legwork to track it down to the buggy conditional. It should be fixed, per this commit:

https://github.com/chrisdavies/tiny-date-picker/commit/84f09891224ecb8da41bbfce8e31b2e28669301a

Tested in IE, FF, Chrome, Safari.

The condition was there originally to ensure that focus was kept on the `A` element so that you could continue to use your arrow keys to move the date selection around. It /appears/ that removing the condition does not negatively affect that scenario or any others I tested.

**Comment by jakubpawlowicz** [comment]
Thanks for issuing the fix so quickly 💯
