### ISSUE TITLE
Including DateRangePicker does not seem to work with Webpack

### ISSUE THREAD

**Issue by hayesr** [chrisdavies/tiny-date-picker#61]
When I try to import DateRangePicker with Webpack, `DateRangePicker` will equal an empty object, if I include it "the old fashioned" way via a script tag, it seems to work.

This logs `{}`:

```javascript
import DateRangePicker from 'tiny-date-picker/date-range-picker';

document.addEventListener("DOMContentLoaded", function() {
  console.log(DateRangePicker);
});
```

This logs `undefined`:

```javascript
import { DateRangePicker } from 'tiny-date-picker/date-range-picker';

document.addEventListener("DOMContentLoaded", function() {
  console.log(DateRangePicker);
});
```

This logs _just_ the TinyDatePicker function:

```javascript
import DateRangePicker from 'tiny-date-picker';

document.addEventListener("DOMContentLoaded", function() {
  console.log(DateRangePicker);
});
```

This logs an object with `TinyDatePicker` and `DateRangePicker`

```javascript
// script tag with tiny-date-picker in <head>

document.addEventListener("DOMContentLoaded", function() {
  console.log(DateRangePicker);
});
```

I'm no expert in Webpack or ES6 imports/exports, but I'd be happy to help if you give me some hints as to where this might be happening.

**Comment by chrisdavies** [comment]
Ah. You're right. It's a typo in my documentation. You need to do this:

`import { DateRangePicker } from 'tiny-date-picker/dist/date-range-picker';`

Note, the "dist". It's not ideal. An alternative would be for me to modify my build to drop the date range picker into root instead of into the dist folder.

The range picker was written pretty quickly as a proof of concept in response to a GitHub issue. So, you may find some rough edges. Let me know if you do!
