### ISSUE TITLE
error showing year view without date selected

### ISSUE THREAD

**Issue by cameronbraid** [chrisdavies/tiny-date-picker#62]
version: "3.1.7"

clicking on the year view without first having a date selected causes the following error 

```
Uncaught TypeError: Cannot read property 'getFullYear' of undefined
    at Object.render$2 [as render] (VM1018 nitro.js:33515)
    at Object.render (VM1018 nitro.js:33711)
    at Object.setState (VM1018 nitro.js:33729)
    at showYearPicker (VM1018 nitro.js:33371)
    at VM1018 nitro.js:33828
    at Array.forEach (<anonymous>)
    at HTMLDivElement.onClick (VM1018 nitro.js:33826)
    at HTMLDivElement.wrapped (VM1018 nitro.js:16953)
```

**Comment by chrisdavies** [comment]
Ah. Interesting. I'll have some time today to look into this.

**Comment by jvalst** [comment]
Same issue over here

**Comment by chrisdavies** [comment]
I can't reproduce this.

What browsers are you using?

Does it happen here? https://chrisdavies.github.io/tiny-date-picker/

Are you doing a custom formatter? That's caused issues like this in the past. It's possible that the format/parse functions don't always get passed a value they expect, so you need to do some checks if you're customizing those.

**Comment by jvalst** [comment]
I can't reproduce it with your example (with Chrome). I'm using a custom formatter indeed, I will have a look into that! Thanks for the quick respons!

**Comment by jvalst** [comment]
Ok, I've found the issue. It was indeed in my parse option. The problem was that I return an Empty string instead of a new Date if the date was not valid / empty. I still have a problem with clicking on the years, the first 2 times, the datepicker closed and shows a "new date". The third time, I can click the years as expected. I've 2 other datepickers on my page, so maybe it has something to do with that.

**Comment by chrisdavies** [comment]
Hm. The demo page also has several date pickers on it. Does it exhibit the close problem that you mention?

If not, it's probably something else. Is it possible that you're initializing the date picker multiple times on the same input?

**Comment by jvalst** [comment]
No I don't have this issue on the demo page. We're using Aurelia's custom attributes for creating the tiny date pickers, so all the elements are the unique datepicker ones. I'm creating 3 datepickers on 3 different elements, so that seems allright. The weird thing, is that it only affects the initial empty one. If I comment the other filled ones out, it happens as well. I will look further into it, think it has to do something with my code. Thanks for the support!

**Comment by jvalst** [comment]
Ok, I've figured out wat was going wrong. The issue is that I was using the statechange event instead of the select event. Statechange was triggering as well on the viewchange. Thanks for your help!

**Comment by chrisdavies** [comment]
Glad you found the root issue!
