### ISSUE TITLE
The "min" option opens the calendar on the minimum date

### ISSUE THREAD

**Issue by subversivo58** [chrisdavies/tiny-date-picker#73]
I am using the `min:` option and it is working as expected however, the calendar is being opened on the min deadline, example:

I use (now 02/03/2018 - 18 => 03/03/2010):

```javascript
// limiter years
let limiter = 18
// field node
let field = document.getElementById('input-date')
// constructor
let datePicker = TinyDatePicker(field, {
     lang: {
         days: [ "Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
         months: [ "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
         today: 'hoje',
         clear: 'limpar',
         close: 'fechar'
     },
     format(dt) {
          return dt.toLocaleString('pt-BR', {
              year: '2-digit',
              month: '2-digit',
              day: '2-digit'
          })
      },
      max: (() => {
          let date = new Date()
          date.setFullYear(date.getFullYear() -limiter)
          return ((date.getFullYear()) + '/' + (date.getMonth() ) + '/' + (date.getDate()))
      })()
})
```
Show this:

![tdp](https://user-images.githubusercontent.com/6475273/38165270-4cc8761e-34e7-11e8-924e-caa5f4bd6453.png)

But I wonder, should not the calendar open on the current date? Should minimum date selection not only "disable" date selection above the minimum date?

Am I wrong to find this behavior strange?

**Comment by chrisdavies** [comment]
I agree that this is strange. If the current date is within the min/max range, I think the current date should be selected. If current date is beyond the max range, I think max should be selected, and if current date is below the min, I think the min should be selected.

Does that make sense?

**Comment by subversivo58** [comment]
Yes, that makes more sense.

Currently if there is no dialog box informed how it works, the user is "half lost" when accessing this interface the first time.

**Comment by chrisdavies** [comment]
Actually, it appears to be working as expected. Try tinkering with following:

```js
TinyDatePicker(field, {
  min: new Date('2018-01-01'),
  max: new Date('2018-12-12'),
});
```

Here's what the calendar shows when I use your example:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/833377/38470440-e5a2d056-3b30-11e8-8cfc-1b00bb0cdb50.png">

It's showing the max date, since the current date is past the max date (which is what is expected). If the current date is within the min / max range, the current date is what shows. If the min date is greater than the current date, the min date is selected. This is the correct behavior, I think.
